Repository kyma-incubator/documentation-component, pull requests merged in 2019-08, with the labels that each got.

#22 Add unit tests for existing functionalities
  .gitattributes
  Makefile
  gulpfile.js
  jest.config.js
  package.json
  packages/documentation-component/src/core/plugins.ts
  packages/documentation-component/src/core/pluginsTests/mocks.ts
  packages/documentation-component/src/core/pluginsTests/plugins.test.ts
  packages/documentation-component/src/helpers/replaceAllLessThanChars.test.ts
  packages/documentation-component/src/interfaces/Plugin.ts
  packages/markdown-render-engine/src/helpers/createBEMClass.test.ts
  packages/markdown-render-engine/src/helpers/createBEMClass.ts
  packages/odata-react/src/ODataReact.tsx
  packages/odata-react/src/components/ErrorComponents/ErrorBoundary.tsx
  packages/odata-react/src/components/ErrorComponents/ErrorComponent.tsx
  packages/odata-react/src/tools/Parser.test.ts
Labels: enhancement

#7 Create documentation for component and related packages
  .prettierignore
  Makefile
  README.md
  docs/README.md
  docs/guidelines/custom-plugin.md
  docs/guidelines/custom-render-engine.md
  docs/props/plugins.md
  docs/props/render-engines.md
  docs/props/sources.md
  docs/templates/document-templates/plugin_README.md
  docs/templates/document-templates/render-engine_README.md
  docs/templates/project-structure-templates/plugin/extractorPlugin.ts
  docs/templates/project-structure-templates/plugin/index.ts
  docs/templates/project-structure-templates/plugin/mutationPlugin.ts
  docs/templates/project-structure-templates/render-engine/index.ts
  docs/templates/project-structure-templates/render-engine/plugins/index.ts
  docs/templates/project-structure-templates/render-engine/renderEngine.tsx
  docs/templates/project-structure-templates/render-engine/types.ts
  package.json
  packages/async-api-render-engine/README.md
  packages/documentation-component/README.md
  packages/markdown-render-engine/README.md
  packages/odata-render-engine/README.md
  packages/open-api-render-engine/README.md
  tsconfig.base.json
  tslint.json
Labels: area/documentation, enhancement

#31 Publish 0.2.0-alpha.1 version
  Makefile
  lerna.json
  package.json
  packages/async-api-render-engine/package.json
  packages/async-api-render-engine/yarn.lock
  packages/documentation-component/package.json
  packages/documentation-component/yarn.lock
  packages/markdown-render-engine/package.json
  packages/markdown-render-engine/yarn.lock
  packages/odata-react/package.json
  packages/odata-react/yarn.lock
  packages/odata-render-engine/package.json
  packages/open-api-render-engine/package.json
  packages/open-api-render-engine/yarn.lock
  yarn.lock
Labels: enhancement

#32 Update git reference in whole package.jsons
  package.json
  packages/async-api-render-engine/package.json
  packages/documentation-component/package.json
  packages/markdown-render-engine/package.json
  packages/odata-react/package.json
  packages/odata-render-engine/package.json
  packages/open-api-render-engine/package.json
Labels: enhancement

#35 Fix depth of update global state of component
  packages/odata-react/package.json
  packages/odata-react/src/components/Table/CollapseButton.tsx
  packages/odata-react/src/components/Table/MainDataTable/CollapsibleRow.tsx
  packages/odata-react/src/components/Table/MainDataTable/Table.tsx
  packages/odata-react/src/components/Table/ServiceDocumentationTable/ServiceDocumentationTable.tsx
  packages/odata-react/src/components/Table/TableContainer.tsx
  packages/odata-react/src/components/styled/CollapseArrow.tsx
  packages/odata-react/src/index.tsx
  packages/odata-react/src/store/index.tsx
Labels: area/core-and-supporting, bug
