Repository kyma-incubator/documentation-component, pull requests merged in 2019-07, with the labels that each got.

#3 Move OData component from console to documentation-component
  .gitignore
  packages/odata-react/Makefile
  packages/odata-react/package.json
  packages/odata-react/public/favicon.ico
  packages/odata-react/public/index.html
  packages/odata-react/src/ODataReact.tsx
  packages/odata-react/src/components/ErrorComponent/ErrorComponent.tsx
  packages/odata-react/src/components/Table/MainDataTable/CollapsibleRow.tsx
  packages/odata-react/src/components/Table/MainDataTable/HideableSubTable.tsx
  packages/odata-react/src/components/Table/MainDataTable/Table.tsx
  packages/odata-react/src/components/Table/ServiceDocumentationTable/CollapsibleAnnotation.tsx
  packages/odata-react/src/components/Table/ServiceDocumentationTable/CollapsibleTable.tsx
  packages/odata-react/src/components/Table/ServiceDocumentationTable/ServiceDocumentationTable.tsx
  packages/odata-react/src/components/Table/ServiceDocumentationTable/SimpleTable.tsx
  packages/odata-react/src/components/Table/TableContainer.tsx
  packages/odata-react/src/components/Table/utils.ts
  packages/odata-react/src/components/styled/styled.ts
  packages/odata-react/src/example/ODataFiles/ODataFav1.ts
  packages/odata-react/src/example/ODataFiles/ODataFav11.ts
  packages/odata-react/src/example/ODataFiles/ODataFav21.ts
  packages/odata-react/src/example/ODataFiles/ODataFav3.ts
  packages/odata-react/src/example/ODataFiles/ODataFav5.ts
  packages/odata-react/src/example/ODataFiles/ODataFavourite3.ts
  packages/odata-react/src/example/ODataFiles/ODataFile.ts
  packages/odata-react/src/example/ODataFiles/ODataFile2.ts
  packages/odata-react/src/example/ODataFiles/ODataNext.ts
  packages/odata-react/src/example/ODataFiles/ODataNorthWindV2.ts
  packages/odata-react/src/example/ODataFiles/ODataProductV2.ts
  packages/odata-react/src/example/ODataFiles/ODataProductV4.ts
  packages/odata-react/src/example/ODataFiles/ODataProductsV3.ts
  packages/odata-react/src/example/ODataFiles/ODataTripV4.ts
  packages/odata-react/src/example/ODataFiles/index.ts
  packages/odata-react/src/index.tsx
  packages/odata-react/src/react-app-env.d.ts
  packages/odata-react/src/tools/Parser.ts
  packages/odata-react/src/tools/Transformer.ts
  packages/odata-react/src/tools/V2V3toV4.ts
  packages/odata-react/src/types.ts
  packages/odata-react/tsconfig.json
  packages/odata-react/tslint.json
  packages/odata-react/yarn.lock
  tsconfig.base.json
Labels: enhancement

#8 Add codeowners to CODEOWNERS file
  CODEOWNERS
Labels: enhancement

#9 Fix design of OData
  packages/odata-react/src/CustomStyles.ts
  packages/odata-react/src/components/Table/ServiceDocumentationTable/ServiceDocumentationTable.tsx
  packages/odata-react/src/index.tsx
Labels: bug

#16 Configure gulp for local development and release process
  .gitignore
  .npmignore
  .prettierignore
  gulpfile.js
  lerna.json
  package-lock.json
  package.json
  packages/async-api-render-engine/package-lock.json
  packages/async-api-render-engine/package.json
  packages/async-api-render-engine/tsconfig.json
  packages/documentation-component/package-lock.json
  packages/documentation-component/package.json
  packages/documentation-component/tsconfig.json
  packages/markdown-render-engine/package-lock.json
  packages/markdown-render-engine/package.json
  packages/markdown-render-engine/tsconfig.json
  packages/odata-react/LICENSE
  packages/odata-react/package.json
  packages/odata-react/tsconfig.json
  packages/odata-render-engine/package-lock.json
  packages/odata-render-engine/package.json
  packages/odata-render-engine/tsconfig.json
  packages/open-api-render-engine/package-lock.json
  packages/open-api-render-engine/package.json
  packages/open-api-render-engine/tsconfig.json
  tsconfig.base.json
Labels: area/core-and-supporting, enhancement

#17 Setup testing framework
  gulpfile.js
  jest.config.js
  lerna.json
  package.json
  packages/async-api-render-engine/package-lock.json
  packages/async-api-render-engine/yarn.lock
  packages/documentation-component/package-lock.json
  packages/documentation-component/src/helpers/toKebabCase.test.ts
  packages/documentation-component/yarn.lock
  packages/markdown-render-engine/package-lock.json
  packages/markdown-render-engine/src/helpers/createBEMClass.test.ts
  packages/markdown-render-engine/yarn.lock
  packages/odata-react/babel.config.js
  packages/odata-react/package-lock.json
  packages/odata-react/package.json
  packages/odata-react/rollup.config.js
  packages/odata-react/src/ODataReact.tsx
  packages/odata-react/src/components/ErrorComponent/ErrorComponent.tsx
  packages/odata-react/src/index.tsx
  packages/odata-react/src/react-app-env.d.ts
  packages/odata-react/src/tools/Parser.test.ts
  packages/odata-react/src/tools/Parser.ts
  packages/odata-react/src/types.ts
  packages/odata-react/yarn.lock
  packages/odata-render-engine/package-lock.json
  packages/odata-render-engine/yarn.lock
  packages/open-api-render-engine/package-lock.json
  packages/open-api-render-engine/yarn.lock
  playground/package-lock.json
  playground/package.json
  playground/yarn.lock
  tsconfig.base.json
  yarn.lock
Labels: area/core-and-supporting

#19 Add working rollup config for documentation-component
  babel.config.js
  gulpfile.js
  package-lock.json
  package.json
  packages/async-api-render-engine/yarn.lock
  packages/documentation-component/package.json
  packages/documentation-component/rollup.config.js
  packages/documentation-component/src/containers/Content/index.tsx
  packages/documentation-component/yarn.lock
  packages/markdown-render-engine/yarn.lock
  packages/odata-react/package.json
  packages/odata-react/rollup.config.js
  packages/odata-react/yarn.lock
  packages/odata-render-engine/yarn.lock
  packages/open-api-render-engine/yarn.lock
  playground/package.json
  playground/yarn.lock
  rollup.base.config.js
  yarn.lock
Labels: enhancement

#20 Fix declaration files in built bundles
  babel.config.js
  package.json
  packages/documentation-component/package.json
  packages/documentation-component/rollup.config.js
  packages/odata-react/babel.config.js
  packages/odata-react/package.json
  packages/odata-react/rollup.config.js
  packages/odata-react/tsconfig.prod.json
  packages/odata-react/yarn.lock
  rollup.base.config.js
  tsconfig.base.json
  yarn.lock
Labels: enhancement

#21 Adapt rollup in gulpfile and fix failing build process by rollup
  gulpfile.js
  package.json
  packages/markdown-render-engine/kyma-project-dc-markdown-render-engine-0.0.1-alpha.0.tgz
  packages/markdown-render-engine/src/plugins/headers/components/provider.tsx
  packages/markdown-render-engine/src/plugins/headers/smoothScroll.ts
  packages/odata-react/yarn.lock
  packages/odata-render-engine/package.json
  packages/odata-render-engine/yarn.lock
  packages/open-api-render-engine/src/renderEngine.tsx
  packages/open-api-render-engine/yarn.lock
  rollup.base.config.js
  yarn.lock
Labels: area/core-and-supporting, bug, enhancement

#25 Create makefile for CI
  Makefile
  gulpfile.js
  milv.config.yaml
  package.json
  packages/odata-react/yarn.lock
  packages/open-api-render-engine/yarn.lock
  playground/README.md
  yarn.lock
Labels: area/ci, area/documentation, enhancement

#23 Improve headers extractor plugin and fix some little bugs in others packages
  packages/documentation-component/kyma-project-documentation-component-0.0.1-alpha.0.tgz
  packages/documentation-component/src/core/plugins.ts
  packages/markdown-render-engine/kyma-project-dc-markdown-render-engine-0.0.1-alpha.0.tgz
  packages/markdown-render-engine/src/MarkdownComponent.tsx
  packages/markdown-render-engine/src/external/index.ts
  packages/markdown-render-engine/src/external/removeMarkdownSyntax.ts
  packages/markdown-render-engine/src/plugins/headers/components/provider.tsx
  packages/markdown-render-engine/src/plugins/headers/extractorPlugin.ts
  packages/markdown-render-engine/src/plugins/headers/scrollSpy.ts
  packages/markdown-render-engine/src/plugins/headers/types.ts
  packages/markdown-render-engine/src/renderers/Heading.tsx
  packages/markdown-render-engine/src/renderers/Link.tsx
  playground/package.json
  playground/yarn.lock
Labels: area/core-and-supporting, bug
