Repository kyma-incubator/documentation-component, pull requests merged in 2022-02, with the labels that each got.

#112 Remove outdated CODEOWNERs from the list
  CODEOWNERS
Labels: area/community, area/documentation, size/XS, lgtm

#110 Bump react-component
  package-lock.json
  packages/async-api-render-engine/package.json
Labels: size/XS, lgtm

#114 Release v0.3.6
  lerna.json
  packages/async-api-render-engine/package-lock.json
  packages/async-api-render-engine/package.json
  packages/documentation-component/package-lock.json
  packages/documentation-component/package.json
  packages/markdown-render-engine/package-lock.json
  packages/markdown-render-engine/package.json
  packages/odata-react/package-lock.json
  packages/odata-react/package.json
  packages/odata-render-engine/package-lock.json
  packages/odata-render-engine/package.json
  packages/open-api-render-engine/package-lock.json
  packages/open-api-render-engine/package.json
Labels: size/S, lgtm
