Repository kyma-incubator/documentation-component, pull requests merged in 2022-01, with the labels that each got.

#103 Bump vulnerable component versions
  package-lock.json
  packages/async-api-render-engine/package-lock.json
  packages/async-api-render-engine/package.json
  packages/documentation-component/package-lock.json
  packages/markdown-render-engine/package-lock.json
  packages/odata-react/package-lock.json
  packages/odata-render-engine/package-lock.json
  packages/open-api-render-engine/package-lock.json
  packages/open-api-render-engine/package.json
Labels: security/critical, size/XS, lgtm

#105 Publish 0.3.5 version
  lerna.json
  packages/async-api-render-engine/package-lock.json
  packages/async-api-render-engine/package.json
  packages/documentation-component/package-lock.json
  packages/documentation-component/package.json
  packages/markdown-render-engine/package-lock.json
  packages/markdown-render-engine/package.json
  packages/odata-react/package-lock.json
  packages/odata-react/package.json
  packages/odata-render-engine/package-lock.json
  packages/odata-render-engine/package.json
  packages/open-api-render-engine/package-lock.json
  packages/open-api-render-engine/package.json
Labels: size/S, lgtm

#109 Add Compass team to CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm
